sudo: false
dist: trusty
install:
- wget -q "https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.tar.gz"
  -O "hugo.tar.gz"
- tar -xzf hugo.tar.gz
script:
- "./hugo"
deploy:
  provider: pages
  repo: balarav/balarav.github.io
  target-branch: master
  skip_cleanup: true
  local_dir: public
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: ###SECURE_TOKEN###